branch-defaults:
  default:
    environment: Projetomodulo3-env
environment-defaults:
  Projetomodulo3-env:
    branch: null
    repository: null
global:
  application_name: projeto_modulo3
  default_ec2_keyname: cepedi-ec2
  default_platform: PHP 8.1 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
